let data={teams:[],players:[],matches:[],updatedAt:null};let monthCursor=new Date();let selectedDate=null;
const $=s=>document.querySelector(s);const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const teamById=id=>data.teams.find(t=>t.id===id);const playerById=id=>data.players.find(p=>p.id===id);
function fmtDate(v){return new Date(v).toLocaleString('es-AR',{dateStyle:'full',timeStyle:'short'})}
function init(){document.querySelectorAll('.tabs button').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tabs button').forEach(x=>x.classList.remove('active'));document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));b.classList.add('active');$('#'+b.dataset.tab).classList.add('active')});$('#prevMonth').onclick=()=>{monthCursor.setMonth(monthCursor.getMonth()-1);renderCalendar()};$('#nextMonth').onclick=()=>{monthCursor.setMonth(monthCursor.getMonth()+1);renderCalendar()};$('#playerTeamFilter').onchange=renderPlayers;$('#statsTeamFilter').onchange=renderStats;renderAll()}
function renderAll(){const updated=data.updatedAt?fmtDate(data.updatedAt):'sin publicar';$('#updated').textContent='Actualizado '+updated;$('#footerUpdated').textContent=updated;$('#teamCount').textContent=data.teams.length;$('#playerCount').textContent=data.players.length;$('#matchCount').textContent=data.matches.length;fillFilters();renderCalendar();renderTeams();renderPlayers();renderStats()}
function fillFilters(){for(const id of ['playerTeamFilter','statsTeamFilter']){const el=$('#'+id),old=el.value;el.innerHTML='<option value="all">Todos los equipos</option>'+data.teams.map(t=>`<option value="${t.id}">${esc(t.name)}</option>`).join('');el.value=data.teams.some(t=>t.id===old)?old:'all'}}
function renderTeams(){const box=$('#teamGrid');box.innerHTML=data.teams.length?data.teams.map(t=>{const ps=data.players.filter(p=>p.teamId===t.id);return `<article class="team-card"><div class="team-title"><img class="logo" src="${t.logo||''}" onerror="this.style.display='none'"><div><h3>${esc(t.name)}</h3><div class="muted">${esc(t.category||'')} · ${ps.length} jugadores</div></div></div></article>`}).join(''):'<div class="card empty">No hay equipos publicados.</div>'}
function renderPlayers(){const filter=$('#playerTeamFilter').value;const ps=data.players.filter(p=>filter==='all'||p.teamId===filter);$('#playerList').innerHTML=ps.length?ps.map(p=>{const t=teamById(p.teamId);const st=playerStats(p.id);return `<div class="player"><div class="number">#${esc(p.number)}</div><div><b>${esc(p.name)}</b><div class="muted">${esc(t?.name||'Sin equipo')} · ${p.type==='goalkeeper'?'Arquero':'Jugador'}</div></div><div><b>${st.goals} G</b> · <b>${st.assists} A</b></div></div>`}).join(''):'<div class="empty">No hay jugadores para mostrar.</div>'}
function completed(){return data.matches.filter(m=>m.status==='completed'&&m.result)}
function playerStats(pid){let goals=0,assists=0;completed().forEach(m=>(m.result.chronology||[]).forEach(e=>{if(e.type==='GOL'){const scorer=playerById(pid);if(scorer&&e.teamId===scorer.teamId&&String(e.number)===String(scorer.number))goals++;if(e.assistNumber!=null&&e.assistNumber!==''&&scorer&&e.teamId===scorer.teamId&&String(e.assistNumber)===String(scorer.number))assists++}}));return {goals,assists,points:goals+assists}}
function renderStats(){const filter=$('#statsTeamFilter').value;const rows=data.players.filter(p=>filter==='all'||p.teamId===filter).map(p=>({...p,st:playerStats(p.id)})).sort((a,b)=>b.st.points-a.st.points||b.st.goals-a.st.goals||b.st.assists-a.st.assists||a.name.localeCompare(b.name));$('#statsBody').innerHTML=rows.length?rows.map(p=>`<tr><td><b>#${esc(p.number)} ${esc(p.name)}</b></td><td>${esc(teamById(p.teamId)?.name||'—')}</td><td>${p.st.goals}</td><td>${p.st.assists}</td><td><b>${p.st.points}</b></td></tr>`).join(''):'<tr><td colspan="5" class="empty">Sin datos.</td></tr>';const standing=data.teams.map(t=>{let pj=0,w=0,d=0,l=0,gf=0,gc=0;completed().forEach(m=>{if(m.home!==t.id&&m.away!==t.id)return;pj++;const hs=m.result.homeScore,as=m.result.awayScore;const home=m.home===t.id;const f=home?hs:as,c=home?as:hs;gf+=f;gc+=c;if(f>c)w++;else if(f===c)d++;else l++});return {t,pj,w,d,l,gf,gc,pts:w*3+d}}).sort((a,b)=>b.pts-a.pts||b.gf-b.gc||b.gf-a.gf||a.t.name.localeCompare(b.t.name));$('#standingsBody').innerHTML=standing.length?standing.map(x=>`<tr><td><b>${esc(x.t.name)}</b></td><td>${x.pj}</td><td>${x.w}</td><td>${x.d}</td><td>${x.l}</td><td>${x.gf}</td><td>${x.gc}</td><td><b>${x.pts}</b></td></tr>`).join(''):'<tr><td colspan="8" class="empty">Sin datos.</td></tr>'}
function renderCalendar(){const y=monthCursor.getFullYear(),m=monthCursor.getMonth();$('#monthLabel').textContent=new Date(y,m,1).toLocaleDateString('es-AR',{month:'long',year:'numeric'});const first=new Date(y,m,1),days=new Date(y,m+1,0).getDate(),offset=(first.getDay()+6)%7;let html=['<div class="dow">Lun</div><div class="dow">Mar</div><div class="dow">Mié</div><div class="dow">Jue</div><div class="dow">Vie</div><div class="dow">Sáb</div><div class="dow">Dom</div>'].join('');for(let i=0;i<offset;i++)html+='<div class="day empty"></div>';for(let d=1;d<=days;d++){const key=`${y}-${String(m+1).padStart(2,'0')}-${String(d).padStart(2,'0')}`;const ms=data.matches.filter(x=>x.date.startsWith(key));const today=new Date().toISOString().slice(0,10);html+=`<div class="day ${selectedDate===key?'selected ':''}${today===key?'today':''}" data-date="${key}"><div class="day-num">${d}${ms.length?` <span class="dot"></span><span class="muted">${ms.length}</span>`:''}</div>${ms.slice(0,2).map(x=>{const h=teamById(x.home)?.name||'Local',a=teamById(x.away)?.name||'Visitante';return `<div class="day-event">${esc(h)} ${x.result?x.result.homeScore+'-'+x.result.awayScore:'vs'} ${esc(a)}</div>`}).join('')}</div>`}$('#calendar').innerHTML=html;document.querySelectorAll('.day[data-date]').forEach(x=>x.onclick=()=>{selectedDate=x.dataset.date;renderCalendar();renderDayMatches()});if(!selectedDate||!selectedDate.startsWith(`${y}-${String(m+1).padStart(2,'0')}`)){const today=new Date();selectedDate=today.getFullYear()===y&&today.getMonth()===m?today.toISOString().slice(0,10):`${y}-${String(m+1).padStart(2,'0')}-01`;renderCalendar();renderDayMatches()}}
function renderDayMatches(){const ms=data.matches.filter(x=>x.date.startsWith(selectedDate||''));$('#dayMatches').innerHTML=ms.length?ms.map(m=>{const h=teamById(m.home),a=teamById(m.away);return `<div class="match"><div><div class="status">${m.status==='completed'?'Finalizado':'Programado'}</div><b>${esc(h?.name||'Local')} vs ${esc(a?.name||'Visitante')}</b><div class="muted">${fmtDate(m.date)}</div></div><div class="score">${m.result?`${m.result.homeScore} - ${m.result.awayScore}`:'—'}</div></div>`}).join(''):'<div class="empty">No hay partidos creados para este día.</div>'}
fetch('data.json?'+Date.now()).then(r=>{if(!r.ok)throw new Error('No data');return r.json()}).then(x=>{data=x;init()}).catch(()=>{$('#updated').textContent='Todavía no hay datos publicados';init()});
